# Generated by Django 4.1.1 on 2022-10-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses_linces_ax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ось (Ax)')),
            ],
            options={
                'verbose_name': 'Ось (Ax)',
                'verbose_name_plural': '(1.7.3) Ось (Ax)',
            },
        ),
        migrations.CreateModel(
            name='Glasses_linces_cyl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Цилиндр (Cyl)')),
            ],
            options={
                'verbose_name': 'Цилиндр (Cyl)',
                'verbose_name_plural': '(1.7.2) Цилиндр (Cyl)',
            },
        ),
        migrations.CreateModel(
            name='Glasses_linces_pd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='РМЦ (PD)')),
            ],
            options={
                'verbose_name': 'РМЦ (PD)',
                'verbose_name_plural': '(1.7.4) РМЦ (PD)',
            },
        ),
        migrations.CreateModel(
            name='Glasses_linces_sph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Сфера (Sph)')),
            ],
            options={
                'verbose_name': 'Сфера (Sph)',
                'verbose_name_plural': '(1.7.1) Сфера (Sph)',
            },
        ),
        migrations.AlterModelOptions(
            name='glasses',
            options={'verbose_name': '[1.0] Очки', 'verbose_name_plural': '(1.0) Очки'},
        ),
        migrations.AlterModelOptions(
            name='glasses_form',
            options={'verbose_name': 'Форма оправы', 'verbose_name_plural': '(1.6) Форма оправ'},
        ),
        migrations.AlterModelOptions(
            name='glasses_frame_material',
            options={'verbose_name': 'Материал оправы', 'verbose_name_plural': '(1.3) Материалы оправ'},
        ),
        migrations.AlterModelOptions(
            name='glasses_frame_type',
            options={'verbose_name': 'Тип оправы', 'verbose_name_plural': '(1.2) Типы оправ'},
        ),
        migrations.AlterModelOptions(
            name='glasses_gender',
            options={'verbose_name': 'Пол', 'verbose_name_plural': '(1.5) Пол'},
        ),
        migrations.AlterModelOptions(
            name='glasses_manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': '(1.1) Производители'},
        ),
        migrations.AlterModelOptions(
            name='glasses_size',
            options={'verbose_name': 'Размер очков', 'verbose_name_plural': '(1.4) Размеры очков'},
        ),
        migrations.RemoveField(
            model_name='glasses',
            name='type',
        ),
        migrations.DeleteModel(
            name='Glasses_type',
        ),
    ]
