# Generated by Django 4.1.1 on 2022-10-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0002_glasses_linces_ax_glasses_linces_cyl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lenses_rad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Радиус (Вс)')),
            ],
            options={
                'verbose_name': 'Радиус линз',
                'verbose_name_plural': '(2.4.2) Радиусы линз',
            },
        ),
        migrations.CreateModel(
            name='Lenses_Sph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Сфера (Sph)')),
            ],
            options={
                'verbose_name': 'Сфера линз',
                'verbose_name_plural': '(2.4.1) Сферы линз',
            },
        ),
        migrations.AlterModelOptions(
            name='lenses',
            options={'verbose_name': 'Линзы', 'verbose_name_plural': '(2.0) Линзы'},
        ),
        migrations.AlterModelOptions(
            name='lenses_manufacturer',
            options={'verbose_name': 'Производитель линз', 'verbose_name_plural': '(2.1) Производители линз'},
        ),
        migrations.AlterModelOptions(
            name='lenses_material',
            options={'verbose_name': 'Материал линз', 'verbose_name_plural': '(2.3) Материалы линз'},
        ),
        migrations.AlterModelOptions(
            name='lenses_type',
            options={'verbose_name': 'Тип линз', 'verbose_name_plural': '(2.2) Типы линз'},
        ),
    ]
